scenarios-space:
  clusters: [250]
  snapshots: [1]
  opts: [Co2L-1H]
  formulation: [angles, kirchhoff]
  gap: [0.01]
  candidates: [1]
  problem: [GTEP]
  region: [DE-NL-LU, FR-BE, ES-PT, GB-IE, IT-CH-AT-LI-SI, CZ-PL-LT-LV-EE, SE-FI-DK-NO, RO-RS-BA-ME-HR-MK-GR-AL-BG-HU-SK]

scenarios-time:
  clusters: [250]
  snapshots: [5]
  opts: [Co2L-1H]
  formulation: [angles, kirchhoff]
  gap: [0.01]
  candidates: [1]
  problem: [GTEP]
  region: [DE-NL-LU, FR-BE, ES-PT, GB-IE, IT-CH-AT-LI-SI, CZ-PL-LT-LV-EE, SE-FI-DK-NO, RO-RS-BA-ME-HR-MK-GR-AL-BG-HU-SK]

iterations: 1
link_unit_p_nom: 1700
synchronizer_circuits: 2
load_shedding: true

milp_solver:
  name: gurobi
  threads: 4
  Method: 3
  TimeLimit: 21600 # 6*3600s
  MIPFocus: 2
  Heuristics: 0.3
  Cuts: 1

lp_solver:
  name: gurobi
  threads: 4
  method: 2 # barrier
  crossover: 0
  BarConvTol: 1.e-5
  FeasibilityTol: 1.e-6
  AggFill: 0
  PreDual: 0
  GURO_PAR_BARDENSETHRESH: 200