scenario:
  clusters: [37]
  ll: ['vopt']
  snapshots: [1,5,100,200,300,400]
  opts: [Co2L0.1-1H, Co2L0.2-1H]
  formulation: [angles, kirchhoff]
  gap: [0.005,0.001]
  lv: [1.0,2.0,3.0]

iterations: 1

solver:
  name: gurobi
  Threads: 8
  Method: 3
  TimeLimit: 40000
  MIPFocus: 2
  Heuristics: 0.3
  Cuts: 1
