name: pypsa-tep
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - pip

  - snakemake-minimal
  - memory_profiler
  
  - six
  - numpy
  - pyomo
  - scipy
  - pandas>=0.24.0
  - matplotlib
  - networkx>=1.10
  - pyomo
  - coincbc
  - glpk

  - ipython
  - jupyter lab

  - conda-forge::cartopy

  - pip:
    - vresutils>=0.2.5
    - git+https://git.scc.kit.edu/FN/pypsa.git@tep#egg=pypsa